from __future__ import annotations

from pathlib import Path
from subprocess import CompletedProcess
from unittest.mock import MagicMock, patch

import pytest

from ptq.application import pr_service
from ptq.application.pr_service import (
    _build_commit_message,
    _build_pr_body,
    _build_pr_title,
    _ensure_ssh_remote,
    create_pr,
    fetch_pr_feedback,
    sync_existing_pr_branch,
)
from ptq.domain.models import JobRecord, PtqError
from ptq.infrastructure.job_repository import JobRepository


class TestPrState:
    def test_get_pr_state_caches(self):
        backend = MagicMock()
        backend.run.return_value = CompletedProcess("", 0, "OPEN\t\n", "")
        pr_service._pr_state_cache.clear()

        first = pr_service.get_pr_state(
            backend, "https://github.com/pytorch/pytorch/pull/99"
        )
        second = pr_service.get_pr_state(
            backend, "https://github.com/pytorch/pytorch/pull/99"
        )

        assert first == "open"
        assert second == "open"
        assert backend.run.call_count == 1

    def test_get_pr_state_closed_with_merged_at_is_merged(self):
        backend = MagicMock()
        backend.run.return_value = CompletedProcess(
            "", 0, "CLOSED\t2026-03-04T10:00:00Z\n", ""
        )
        pr_service._pr_state_cache.clear()

        state = pr_service.get_pr_state(
            backend, "https://github.com/pytorch/pytorch/pull/100", force_refresh=True
        )
        assert state == "merged"


class TestBuildPrBody:
    def test_omits_human_note(self):
        body = _build_pr_body(
            "Report", "", "", issue_number=42, human_note="Trivial fix"
        )
        assert "## Human Note" not in body
        assert "Trivial fix" not in body
        assert "Fixes #42" in body

    def test_agent_report_keeps_useful_sections(self):
        report = """# Issue

## Summary
Short summary.

## Root cause
Root cause details.

## Fix
Fix details.

## Repro
Reporter repro details.

## Test results
A new regression test was added.

## Backward compatibility analysis
Raw DTensor to_local identity behavior is unchanged.
"""
        body = _build_pr_body(
            report,
            "",
            "print('repro')",
            issue_number=42,
            human_note="Note",
            status={"repro_file": "repro_42_generated.py"},
        )
        assert "## Agent Report" in body
        assert "### Summary\nShort summary." in body
        assert "### Root Cause\nRoot cause details." in body
        assert "### Fix\nFix details." in body
        assert "### Repro" in body
        assert "python repro_42_generated.py" in body
        assert "print('repro')" in body
        assert "### Testing\nA new regression test was added." in body
        assert (
            "### Backward Compatibility\n"
            "Raw DTensor to_local identity behavior is unchanged."
        ) in body

    def test_does_not_dump_worklog(self):
        body = _build_pr_body(
            "Report", "log entries", "", issue_number=None, human_note="N"
        )
        assert "log entries" not in body
        assert "Agent Worklog" not in body

    def test_no_agent_content(self):
        body = _build_pr_body("", "", "", issue_number=None, human_note="Manual fix")
        assert "Manual fix" not in body
        assert "Human Note" not in body
        assert "This PR was generated by" in body

    def test_issue_reference(self):
        body = _build_pr_body("R", "", "", issue_number=99, human_note="Fix")
        assert "Fixes #99" in body

    def test_repro_is_in_pr_body_not_separate_comment(self):
        body = _build_pr_body(
            "R",
            "",
            "import torch\nprint(torch.__version__)",
            issue_number=42,
            human_note="Fix",
            repro_filename="repro_42_generated.py",
        )
        assert "### Repro" in body
        assert "python repro_42_generated.py" in body
        assert "Repro Script" in body
        assert "import torch" in body

    def test_no_repro(self):
        body = _build_pr_body("R", "", "", issue_number=42, human_note="Fix")
        assert "```bash\npython repro.py\n```" in body

    def test_includes_status_summary_and_files_changed(self):
        body = _build_pr_body(
            "Long report",
            "Long worklog",
            "",
            issue_number=42,
            human_note="Note",
            status={
                "summary": "Preserve Parameter-ness in DTensor.to_local().",
                "files_changed": [
                    "torch/distributed/tensor/_api.py",
                    "test/distributed/tensor/test_dtensor.py",
                ],
            },
        )
        assert "## Agent Report" in body
        assert "Preserve Parameter-ness in DTensor.to_local()." in body
        assert "- `torch/distributed/tensor/_api.py`" in body
        assert "- `test/distributed/tensor/test_dtensor.py`" in body

    def test_status_summary_omits_iteration_and_reviewer_chatter(self):
        body = _build_pr_body(
            "",
            "",
            "",
            issue_number=42,
            human_note="Note",
            status={
                "summary": (
                    "DTensor.to_local dropped _is_param. Fix stamps _is_param "
                    "on the returned tensor. Run 4 addresses evaluator feedback: "
                    "gpt-5.5 blocking and claude-opus-4-7 nit. spin fixlint clean."
                )
            },
        )
        assert "DTensor.to_local dropped _is_param." in body
        assert "Fix stamps _is_param on the returned tensor." in body
        assert "Run 4" not in body
        assert "gpt-5.5" not in body
        assert "claude-opus" not in body

    def test_agent_report_does_not_truncate_useful_sections(self):
        long_fix = "Preserve DTensor parameter metadata. " + ("details " * 400)
        report = f"""## Summary
Summary.

## Fix
{long_fix}

## Test results
Tests passed.
"""
        body = _build_pr_body(report, "", "", issue_number=42, human_note="Note")
        assert long_fix.strip() in body
        assert "details..." not in body

    def test_agent_report_removes_review_provenance_from_pr_body(self):
        report = """## Test results
I also added a regression test RedistributeTest.test_shard_to_replicate_local_tensor_contiguous in test/distributed/tensor/test_redistribute.py modeled on the example referenced by @aditvenk on the draft PR (see PR #174134). It iterates over shape cases and asserts local tensor contiguity.
"""
        body = _build_pr_body(report, "", "", issue_number=42, human_note="Note")
        assert (
            "RedistributeTest.test_shard_to_replicate_local_tensor_contiguous"
            in body
        )
        assert "shape cases" in body
        assert "@aditvenk" not in body
        assert "draft PR" not in body
        assert "PR #174134" not in body
        assert "modeled on" not in body
        assert "referenced by" not in body


class TestBuildCommitMessage:
    def test_includes_summary_and_fixes_footer(self):
        message = _build_commit_message(
            "Fix #42",
            issue_number=42,
            human_note="Human note",
            report="The reducer now reports mismatched parameter shapes.",
            status={"summary": "Validate parameter metadata across ranks."},
        )
        assert message.startswith("Fix #42\n\nSummary:\n")
        assert "- Validate parameter metadata across ranks." in message
        assert message.rstrip().endswith("Fixes #42")


class TestBuildPrTitle:
    def test_prefers_explicit_title(self):
        title = _build_pr_title(
            "Preserve DTensor parameter markers",
            status={"pr_title": "Status title"},
            report="",
        )
        assert title == "Preserve DTensor parameter markers"

    def test_uses_status_pr_title(self):
        title = _build_pr_title(
            None,
            status={"pr_title": "Preserve Parameter markers in DTensor.to_local"},
            report="",
        )
        assert title == "Preserve Parameter markers in DTensor.to_local"

    def test_falls_back_to_status_summary_without_issue_reference(self):
        title = _build_pr_title(
            None,
            status={
                "summary": (
                    "Preserve Parameter markers in DTensor.to_local. Fixes #166156"
                )
            },
            report="",
        )
        assert title == "Preserve Parameter markers in DTensor.to_local"

    def test_does_not_truncate_status_pr_title(self):
        long_title = (
            "Preserve Parameter markers in DTensor.to_local without mutating the "
            "underlying local tensor returned by existing raw DTensor calls"
        )
        title = _build_pr_title(None, status={"pr_title": long_title}, report="")
        assert title == long_title
        assert not title.endswith("...")

    def test_derives_fix_oriented_dtensor_title_from_bug_summary(self):
        title = _build_pr_title(
            None,
            status={
                "summary": (
                    "DTensor.to_local() drops the _is_param marker that nn.Parameter "
                    "sets on custom-tensor instances, so nn.Parameter(dtensor)."
                    "to_local() returned a plain tensor (gh-166156). Fix stamps "
                    "_is_param on the returned tensor."
                )
            },
            report="",
        )
        assert title == "Preserve Parameter markers in DTensor.to_local"
        assert "drops" not in title


class TestEnsureSshRemote:
    def test_converts_https_to_ssh(self):
        backend = MagicMock()
        backend.run.return_value = MagicMock(
            stdout="https://github.com/pytorch/pytorch\n", returncode=0
        )
        _ensure_ssh_remote(backend, "/worktree", lambda _: None)
        set_url_call = [c for c in backend.run.call_args_list if "set-url" in str(c)]
        assert len(set_url_call) == 1
        assert "git@github.com:pytorch/pytorch.git" in str(set_url_call[0])

    def test_already_ssh_no_op(self):
        backend = MagicMock()
        backend.run.return_value = MagicMock(
            stdout="git@github.com:pytorch/pytorch.git\n", returncode=0
        )
        _ensure_ssh_remote(backend, "/worktree", lambda _: None)
        assert all("set-url" not in str(c) for c in backend.run.call_args_list)


class TestCreatePr:
    def _setup(self, tmp_path: Path) -> tuple[JobRepository, MagicMock]:
        repo = JobRepository(tmp_path / "jobs.json")
        repo.save(
            JobRecord(
                job_id="20260217-42",
                issue=42,
                machine="gpu-dev",
                workspace="~/ptq_workspace",
            )
        )
        backend = MagicMock()
        backend.workspace = "~/ptq_workspace"

        def run_side_effect(cmd, check=True):
            if "git ls-remote --exit-code --heads origin" in cmd:
                return CompletedProcess("", 1, "", "")
            if "git remote get-url" in cmd:
                return CompletedProcess("", 0, "git@github.com:pytorch/pytorch.git\n")
            if "git merge-base" in cmd:
                return CompletedProcess("", 0, "abc123\n")
            if "gh pr create" in cmd:
                return CompletedProcess(
                    "", 0, "https://github.com/pytorch/pytorch/pull/99\n"
                )
            return CompletedProcess("", 0, "")

        backend.run = MagicMock(side_effect=run_side_effect)
        return repo, backend

    def test_creates_pr(self, tmp_path):
        repo, backend = self._setup(tmp_path)
        with patch("ptq.application.pr_service.backend_for_job", return_value=backend):
            result = create_pr(repo, "20260217-42", human_note="Trivial fix")
        assert result.url == "https://github.com/pytorch/pytorch/pull/99"
        assert result.branch == "ptq/42"
        assert (
            repo.get("20260217-42").pr_url
            == "https://github.com/pytorch/pytorch/pull/99"
        )

    def test_empty_note_raises(self, tmp_path):
        repo, backend = self._setup(tmp_path)
        with (
            patch("ptq.application.pr_service.backend_for_job", return_value=backend),
            pytest.raises(PtqError, match="human note is required"),
        ):
            create_pr(repo, "20260217-42", human_note="")

    def test_custom_title(self, tmp_path):
        repo, backend = self._setup(tmp_path)
        with patch("ptq.application.pr_service.backend_for_job", return_value=backend):
            result = create_pr(
                repo, "20260217-42", human_note="Note", title="Custom Title"
            )
        assert result.branch == "ptq/42"

    def test_default_title_is_generic_without_solver_metadata(self, tmp_path):
        repo, backend = self._setup(tmp_path)
        with patch("ptq.application.pr_service.backend_for_job", return_value=backend):
            create_pr(repo, "20260217-42", human_note="Trivial fix")
        create_calls = [
            call
            for call in backend.run.call_args_list
            if "gh pr create" in str(call)
        ]
        assert len(create_calls) == 1
        assert "Fix #42" not in str(create_calls[0])
        assert "Apply PTQ-generated PyTorch fix" in str(create_calls[0])

    def test_pr_title_uses_status_metadata(self, tmp_path):
        repo, backend = self._setup(tmp_path)

        def run_side_effect(cmd, check=True):
            if "cat ~/ptq_workspace/jobs/20260217-42/status.json" in cmd:
                return CompletedProcess(
                    "",
                    0,
                    '{"pr_title": "Preserve Parameter markers in DTensor.to_local"}',
                    "",
                )
            if "cat ~/ptq_workspace/jobs/20260217-42/" in cmd:
                return CompletedProcess("", 1, "", "")
            if "git remote get-url" in cmd:
                return CompletedProcess("", 0, "git@github.com:pytorch/pytorch.git\n")
            if "gh pr create" in cmd:
                return CompletedProcess(
                    "", 0, "https://github.com/pytorch/pytorch/pull/99\n"
                )
            return CompletedProcess("", 0, "")

        backend.run = MagicMock(side_effect=run_side_effect)
        with patch("ptq.application.pr_service.backend_for_job", return_value=backend):
            create_pr(repo, "20260217-42", human_note="Trivial fix")
        create_calls = [
            call
            for call in backend.run.call_args_list
            if "gh pr create" in str(call)
        ]
        assert len(create_calls) == 1
        assert "Preserve Parameter markers in DTensor.to_local" in str(create_calls[0])

    def test_updates_known_open_pr(self, tmp_path):
        repo, backend = self._setup(tmp_path)
        job = repo.get("20260217-42")
        job.pr_url = "https://github.com/pytorch/pytorch/pull/77"
        repo.save(job)

        def run_side_effect(cmd, check=True):
            if "gh pr view" in cmd:
                return CompletedProcess("", 0, "OPEN\t\n", "")
            if "gh pr edit 'https://github.com/pytorch/pytorch/pull/77'" in cmd:
                return CompletedProcess("", 0, "", "")
            if "git remote get-url" in cmd:
                return CompletedProcess("", 0, "git@github.com:pytorch/pytorch.git\n")
            if "git merge-base" in cmd:
                return CompletedProcess("", 0, "abc123\n")
            if "gh pr create" in cmd:
                return CompletedProcess("", 1, "", "should not create")
            return CompletedProcess("", 0, "")

        backend.run = MagicMock(side_effect=run_side_effect)
        with patch("ptq.application.pr_service.backend_for_job", return_value=backend):
            result = create_pr(repo, "20260217-42", human_note="Updated note")
        assert result.url == "https://github.com/pytorch/pytorch/pull/77"
        create_calls = [
            c for c in backend.run.call_args_list if "gh pr create" in str(c)
        ]
        assert not create_calls

    def test_updates_existing_pr_from_remote_branch(self, tmp_path):
        repo, backend = self._setup(tmp_path)
        job = repo.get("20260217-42")
        job.pr_url = "https://github.com/pytorch/pytorch/pull/77"
        repo.save(job)

        def run_side_effect(cmd, check=True):
            if "gh pr view" in cmd:
                return CompletedProcess("", 0, "OPEN\t\n", "")
            if "git ls-remote --exit-code --heads origin ptq/42" in cmd:
                return CompletedProcess("", 0, "abc\trefs/heads/ptq/42\n", "")
            if "fetch --no-recurse-submodules origin ptq/42" in cmd:
                return CompletedProcess("", 0, "", "")
            if "git status --porcelain" in cmd:
                return CompletedProcess("", 0, " M torch/foo.py\n", "")
            if "git stash push -u -m ptq-sync-existing-pr" in cmd:
                return CompletedProcess("", 0, "Saved working directory", "")
            if "git branch --show-current" in cmd:
                return CompletedProcess("", 0, "ptq-20260217-42\n", "")
            if "git checkout -B ptq/42 FETCH_HEAD" in cmd:
                return CompletedProcess("", 0, "", "")
            if "git stash pop" in cmd:
                return CompletedProcess("", 0, "", "")
            if "gh pr edit 'https://github.com/pytorch/pytorch/pull/77'" in cmd:
                return CompletedProcess("", 0, "", "")
            if "git remote get-url" in cmd:
                return CompletedProcess("", 0, "git@github.com:pytorch/pytorch.git\n")
            return CompletedProcess("", 0, "")

        backend.run = MagicMock(side_effect=run_side_effect)
        with patch("ptq.application.pr_service.backend_for_job", return_value=backend):
            result = create_pr(repo, "20260217-42", human_note="Updated note")

        assert result.url == "https://github.com/pytorch/pytorch/pull/77"
        commands = [call.args[0] for call in backend.run.call_args_list]
        fetch_idx = next(
            i
            for i, cmd in enumerate(commands)
            if "fetch --no-recurse-submodules origin ptq/42" in cmd
        )
        add_idx = next(i for i, cmd in enumerate(commands) if "git add -A" in cmd)
        assert fetch_idx < add_idx
        assert any("git stash pop" in cmd for cmd in commands)

    def test_pushes_pytorch_pr_when_support_worktree_has_only_fix(self, tmp_path):
        repo = JobRepository(tmp_path / "jobs.json")
        repo.save(
            JobRecord(
                job_id="20260520-torchtitan-3409",
                issue=3409,
                machine="gpu-dev",
                workspace="~/ptq_workspace",
                repo="torchtitan",
                pr_url="https://github.com/pytorch/torchtitan/pull/3421",
            )
        )
        backend = MagicMock()
        backend.workspace = "~/ptq_workspace"

        def run_side_effect(cmd, check=True):
            if (
                "cat ~/ptq_workspace/jobs/20260520-torchtitan-3409/pytorch-fix.diff"
                in cmd
            ):
                return CompletedProcess(
                    "",
                    0,
                    "diff --git a/torch/foo.py b/torch/foo.py",
                    "",
                )
            if "cat ~/ptq_workspace/jobs/20260520-torchtitan-3409/report.md" in cmd:
                return CompletedProcess("", 0, "## Summary\nFix is in PyTorch.", "")
            if "cat ~/ptq_workspace/jobs/20260520-torchtitan-3409/status.json" in cmd:
                return CompletedProcess(
                    "", 0, '{"pr_title": "Fix local tensor op"}', ""
                )
            if "cat ~/ptq_workspace/jobs/20260520-torchtitan-3409/" in cmd:
                return CompletedProcess("", 1, "", "")
            if (
                "cd ~/ptq_workspace/jobs/20260520-torchtitan-3409/torchtitan"
                in cmd
                and "git status --porcelain" in cmd
            ):
                return CompletedProcess("", 0, "", "")
            if "git ls-remote --exit-code --heads origin ptq/torchtitan-3409" in cmd:
                return CompletedProcess("", 1, "", "")
            if "git remote get-url" in cmd:
                return CompletedProcess("", 0, "git@github.com:pytorch/pytorch.git\n")
            if "git diff --cached --quiet" in cmd:
                return CompletedProcess("", 1, "", "")
            if "gh pr create" in cmd:
                return CompletedProcess(
                    "", 0, "https://github.com/pytorch/pytorch/pull/185000\n", ""
                )
            return CompletedProcess("", 0, "")

        backend.run = MagicMock(side_effect=run_side_effect)
        with patch("ptq.application.pr_service.backend_for_job", return_value=backend):
            result = create_pr(repo, "20260520-torchtitan-3409", human_note="Fix")

        assert result.url == "https://github.com/pytorch/pytorch/pull/185000"
        assert result.branch == "ptq/torchtitan-3409"
        commands = [call.args[0] for call in backend.run.call_args_list]
        assert any(
            "cd ~/ptq_workspace/jobs/20260520-torchtitan-3409/pytorch"
            in cmd
            and "git checkout -B ptq/torchtitan-3409" in cmd
            for cmd in commands
        )
        create_cmd = next(cmd for cmd in commands if "gh pr create" in cmd)
        assert "Fixes pytorch/torchtitan#3409" in create_cmd
        assert "pytorch/torchtitan/pull/3421" not in create_cmd

    def test_closed_saved_pr_creates_new_pr(self, tmp_path):
        repo, backend = self._setup(tmp_path)
        job = repo.get("20260217-42")
        job.pr_url = "https://github.com/pytorch/pytorch/pull/77"
        repo.save(job)

        def run_side_effect(cmd, check=True):
            if "gh pr view" in cmd:
                return CompletedProcess("", 0, "CLOSED\t\n", "")
            if "git remote get-url" in cmd:
                return CompletedProcess("", 0, "git@github.com:pytorch/pytorch.git\n")
            if "git merge-base" in cmd:
                return CompletedProcess("", 0, "abc123\n")
            if "gh pr create" in cmd:
                return CompletedProcess(
                    "", 0, "https://github.com/pytorch/pytorch/pull/101\n", ""
                )
            return CompletedProcess("", 0, "")

        backend.run = MagicMock(side_effect=run_side_effect)
        with patch("ptq.application.pr_service.backend_for_job", return_value=backend):
            result = create_pr(repo, "20260217-42", human_note="Updated note")
        assert result.url == "https://github.com/pytorch/pytorch/pull/101"

    def test_handles_existing_pr(self, tmp_path):
        repo, backend = self._setup(tmp_path)

        def run_side_effect(cmd, check=True):
            if "git remote get-url" in cmd:
                return CompletedProcess("", 0, "git@github.com:pytorch/pytorch.git\n")
            if "git merge-base" in cmd:
                return CompletedProcess("", 0, "abc123\n")
            if "gh pr create" in cmd:
                return CompletedProcess("", 1, "", "already exists")
            if "gh pr list" in cmd:
                return CompletedProcess(
                    "", 0, "https://github.com/pytorch/pytorch/pull/88\n"
                )
            return CompletedProcess("", 0, "")

        backend.run = MagicMock(side_effect=run_side_effect)
        with patch("ptq.application.pr_service.backend_for_job", return_value=backend):
            result = create_pr(repo, "20260217-42", human_note="Updated note")
        assert result.url == "https://github.com/pytorch/pytorch/pull/88"
        assert (
            repo.get("20260217-42").pr_url
            == "https://github.com/pytorch/pytorch/pull/88"
        )
        edit_calls = [c for c in backend.run.call_args_list if "gh pr edit" in str(c)]
        assert len(edit_calls) == 1
        assert "Updated note" not in str(edit_calls[0])
        assert "This PR was generated by" in str(edit_calls[0])

    def test_failure_raises(self, tmp_path):
        repo, backend = self._setup(tmp_path)

        def run_side_effect(cmd, check=True):
            if "gh pr create" in cmd:
                return CompletedProcess("", 1, "", "auth required")
            if "git merge-base" in cmd:
                return CompletedProcess("", 0, "abc123\n")
            if "git remote get-url" in cmd:
                return CompletedProcess("", 0, "git@github.com:pytorch/pytorch.git\n")
            return CompletedProcess("", 0, "")

        backend.run = MagicMock(side_effect=run_side_effect)
        with (
            patch("ptq.application.pr_service.backend_for_job", return_value=backend),
            pytest.raises(PtqError, match="gh pr create failed"),
        ):
            create_pr(repo, "20260217-42", human_note="Fix")

    def test_pushes_without_force(self, tmp_path):
        repo, backend = self._setup(tmp_path)
        with patch("ptq.application.pr_service.backend_for_job", return_value=backend):
            create_pr(repo, "20260217-42", human_note="Trivial fix")
        push_calls = [
            call
            for call in backend.run.call_args_list
            if "git push -u origin" in str(call)
        ]
        assert len(push_calls) == 1
        assert "--force" not in str(push_calls[0])

    def test_push_rebases_and_retries_on_fetch_first(self, tmp_path):
        repo, backend = self._setup(tmp_path)
        push_attempts = 0

        def run_side_effect(cmd, check=True):
            nonlocal push_attempts
            if "git ls-remote --exit-code --heads origin" in cmd:
                return CompletedProcess("", 1, "", "")
            if "git remote get-url" in cmd:
                return CompletedProcess("", 0, "git@github.com:pytorch/pytorch.git\n")
            if "git push -u origin ptq/42" in cmd:
                push_attempts += 1
                if push_attempts == 1:
                    return CompletedProcess("", 1, "", "error: fetch first")
                return CompletedProcess("", 0, "", "")
            if "fetch --no-recurse-submodules origin ptq/42" in cmd:
                return CompletedProcess("", 0, "", "")
            if "git rebase FETCH_HEAD" in cmd:
                return CompletedProcess("", 0, "", "")
            if "gh pr create" in cmd:
                return CompletedProcess(
                    "", 0, "https://github.com/pytorch/pytorch/pull/99\n"
                )
            return CompletedProcess("", 0, "")

        backend.run = MagicMock(side_effect=run_side_effect)
        with patch("ptq.application.pr_service.backend_for_job", return_value=backend):
            create_pr(repo, "20260217-42", human_note="Trivial fix")

        commands = [call.args[0] for call in backend.run.call_args_list]
        assert push_attempts == 2
        assert any(
            "fetch --no-recurse-submodules origin ptq/42" in cmd
            for cmd in commands
        )
        assert any("git rebase FETCH_HEAD" in cmd for cmd in commands)

    def test_pr_create_is_always_draft(self, tmp_path):
        repo, backend = self._setup(tmp_path)
        with patch("ptq.application.pr_service.backend_for_job", return_value=backend):
            create_pr(repo, "20260217-42", human_note="Trivial fix", draft=False)
        create_calls = [
            call
            for call in backend.run.call_args_list
            if "gh pr create" in str(call)
        ]
        assert len(create_calls) == 1
        assert "--draft" in str(create_calls[0])

    def test_gh_pr_create_gets_proxy_env_prefix(self, tmp_path):
        repo, backend = self._setup(tmp_path)
        with (
            patch("ptq.application.pr_service.backend_for_job", return_value=backend),
            patch.dict(
                "os.environ",
                {
                    "PATH": "/usr/bin",
                    "HOME": "/tmp",
                },
                clear=True,
            ),
        ):
            create_pr(repo, "20260217-42", human_note="Trivial fix")
        create_calls = [
            call
            for call in backend.run.call_args_list
            if "gh pr create" in str(call)
        ]
        assert len(create_calls) == 1
        call_text = str(create_calls[0])
        assert "https_proxy=http://fwdproxy:8080" in call_text
        assert "HTTPS_PROXY=http://fwdproxy:8080" in call_text

    def test_commit_uses_file_with_fixes_footer(self, tmp_path):
        repo, backend = self._setup(tmp_path)

        def run_side_effect(cmd, check=True):
            if "git diff --cached --quiet" in cmd:
                return CompletedProcess("", 1, "", "")
            if "git remote get-url" in cmd:
                return CompletedProcess("", 0, "git@github.com:pytorch/pytorch.git\n")
            if "gh pr create" in cmd:
                return CompletedProcess(
                    "", 0, "https://github.com/pytorch/pytorch/pull/99\n"
                )
            return CompletedProcess("", 0, "")

        backend.run = MagicMock(side_effect=run_side_effect)
        with patch("ptq.application.pr_service.backend_for_job", return_value=backend):
            create_pr(repo, "20260217-42", human_note="Trivial fix")
        commit_calls = [
            call
            for call in backend.run.call_args_list
            if "git commit -F" in str(call)
        ]
        assert len(commit_calls) == 1
        printf_calls = [
            call
            for call in backend.run.call_args_list
            if "printf %s" in str(call)
        ]
        assert len(printf_calls) == 1
        assert "Fixes #42" in str(printf_calls[0])

    def test_deletes_old_separate_repro_script_comment(self, tmp_path):
        repo, backend = self._setup(tmp_path)

        def run_side_effect(cmd, check=True):
            if "cat ~/ptq_workspace/jobs/20260217-42/status.json" in cmd:
                return CompletedProcess(
                    "",
                    0,
                    '{"repro_file": "repro_42.py", "repro_source": "from_issue"}',
                    "",
                )
            if "cat ~/ptq_workspace/jobs/20260217-42/repro_42.py" in cmd:
                return CompletedProcess("", 0, "print('from issue')", "")
            if "cat ~/ptq_workspace/jobs/20260217-42/" in cmd:
                return CompletedProcess("", 1, "", "")
            if "git remote get-url" in cmd:
                return CompletedProcess("", 0, "git@github.com:pytorch/pytorch.git\n")
            if "gh pr create" in cmd:
                return CompletedProcess(
                    "", 0, "https://github.com/pytorch/pytorch/pull/99\n"
                )
            if "gh api repos/pytorch/pytorch/issues/99/comments" in cmd:
                return CompletedProcess(
                    "",
                    0,
                    '[{"id": 123, "body": "<!-- ptq:repro-script -->\\nold"}]',
                    "",
                )
            if "gh api -X DELETE repos/pytorch/pytorch/issues/comments/123" in cmd:
                return CompletedProcess("", 0, "", "")
            return CompletedProcess("", 0, "")

        backend.run = MagicMock(side_effect=run_side_effect)
        with patch("ptq.application.pr_service.backend_for_job", return_value=backend):
            create_pr(repo, "20260217-42", human_note="Trivial fix")
        comment_calls = [
            call
            for call in backend.run.call_args_list
            if "gh pr comment" in str(call)
        ]
        assert not comment_calls
        delete_calls = [
            call
            for call in backend.run.call_args_list
            if "gh api -X DELETE repos/pytorch/pytorch/issues/comments/123" in str(call)
        ]
        assert len(delete_calls) == 1
        create_calls = [
            call
            for call in backend.run.call_args_list
            if "gh pr create" in str(call)
        ]
        command = create_calls[0].args[0]
        assert "python repro_42.py" in command
        assert "from issue" in command

    def test_fetches_pr_feedback_from_existing_open_pr(self, tmp_path):
        repo, backend = self._setup(tmp_path)
        job = repo.get("20260217-42")
        job.pr_url = "https://github.com/pytorch/pytorch/pull/99"
        repo.save(job)

        def run_side_effect(cmd, check=True):
            if "gh pr view" in cmd:
                return CompletedProcess("", 0, "OPEN\t\n", "")
            if "gh api repos/pytorch/pytorch/issues/99/comments" in cmd:
                return CompletedProcess(
                    "",
                    0,
                    (
                        '[{"body": "Please add a regression test.", '
                        '"id": 111, '
                        '"user": {"login": "reviewer"}, '
                        '"html_url": "https://github.com/pytorch/pytorch/pull/99#issuecomment-1"},'
                        '{"body": "<!-- ptq:repro-script -->\\nold", '
                        '"user": {"login": "bot"}},'
                        '{"body": "[bot] Resolved in latest update.\\n\\n'
                        '<!-- ptq:resolution:112 -->", '
                        '"id": 112, "user": {"login": "ptq-bot"}},'
                        '{"body": "[bot] Claude review: add the BC test.", '
                        '"id": 113, "user": {"login": "claude-review-bot"}}]'
                    ),
                    "",
                )
            if "gh api repos/pytorch/pytorch/pulls/99/comments" in cmd:
                return CompletedProcess(
                    "",
                    0,
                    (
                        '[{"body": "This misses the no_grad case.", '
                        '"id": 222, '
                        '"path": "torch/foo.py", "line": 12, '
                        '"user": {"login": "reviewer2"}}]'
                    ),
                    "",
                )
            if "gh api repos/pytorch/pytorch/pulls/99/reviews" in cmd:
                return CompletedProcess(
                    "",
                    0,
                    '[{"body": "Changes requested.", "id": 333, '
                    '"state": "CHANGES_REQUESTED", '
                    '"user": {"login": "reviewer3"}}]',
                    "",
                )
            if "gh pr checks https://github.com/pytorch/pytorch/pull/99" in cmd:
                return CompletedProcess(
                    "",
                    1,
                    (
                        '[{"name": "linux-test", "bucket": "fail", '
                        '"state": "FAILURE", "workflow": "pull", '
                        '"description": "test failed", '
                        '"link": "https://github.com/pytorch/pytorch/actions/runs/1"},'
                        '{"name": "lint", "bucket": "pass", "state": "SUCCESS"}]'
                    ),
                    "",
                )
            if "gh run view 1 --repo pytorch/pytorch --log-failed" in cmd:
                return CompletedProcess(
                    "",
                    0,
                    "linux-test\tRun tests\tFAILED test_dtensor.py::test_case",
                    "",
                )
            return CompletedProcess("", 0, "")

        backend.run = MagicMock(side_effect=run_side_effect)
        with patch("ptq.application.pr_service.backend_for_job", return_value=backend):
            feedback = fetch_pr_feedback(repo, "20260217-42")

        assert feedback is not None
        assert feedback["pr_url"] == "https://github.com/pytorch/pytorch/pull/99"
        assert len(feedback["comments"]) == 4
        assert feedback["comments"][0]["kind"] == "conversation"
        assert feedback["comments"][0]["id"] == 111
        assert feedback["comments"][1]["id"] == 113
        assert feedback["comments"][1]["author"] == "claude-review-bot"
        assert feedback["comments"][1]["body"].startswith("[bot] Claude review")
        assert feedback["comments"][2]["path"] == "torch/foo.py"
        assert feedback["comments"][3]["state"] == "CHANGES_REQUESTED"
        assert all("ptq:repro-script" not in c["body"] for c in feedback["comments"])
        assert all("ptq:resolution:" not in c["body"] for c in feedback["comments"])
        assert len(feedback["ci_failures"]) == 1
        assert feedback["ci_failures"][0]["name"] == "linux-test"
        assert feedback["ci_failures"][0]["link"].endswith("/actions/runs/1")
        assert "FAILED test_dtensor.py::test_case" in feedback["ci_failures"][0][
            "failed_log_excerpt"
        ]

    def test_fetches_pr_feedback_when_only_ci_is_failing(self, tmp_path):
        repo, backend = self._setup(tmp_path)
        job = repo.get("20260217-42")
        job.pr_url = "https://github.com/pytorch/pytorch/pull/99"
        repo.save(job)

        def run_side_effect(cmd, check=True):
            if "gh pr view" in cmd:
                return CompletedProcess("", 0, "OPEN\t\n", "")
            if "gh api repos/pytorch/pytorch/issues/99/comments" in cmd:
                return CompletedProcess("", 0, "[]", "")
            if "gh api repos/pytorch/pytorch/pulls/99/comments" in cmd:
                return CompletedProcess("", 0, "[]", "")
            if "gh api repos/pytorch/pytorch/pulls/99/reviews" in cmd:
                return CompletedProcess("", 0, "[]", "")
            if "gh pr checks https://github.com/pytorch/pytorch/pull/99" in cmd:
                return CompletedProcess(
                    "",
                    1,
                    '[{"name": "distributed / test", "bucket": "fail", '
                    '"state": "FAILURE", "description": "Timeout", '
                    '"link": "https://github.com/pytorch/pytorch/actions/runs/2"}]',
                    "",
                )
            if "gh run view 2 --repo pytorch/pytorch --log-failed" in cmd:
                return CompletedProcess("", 0, "distributed test timed out", "")
            return CompletedProcess("", 0, "")

        backend.run = MagicMock(side_effect=run_side_effect)
        with patch("ptq.application.pr_service.backend_for_job", return_value=backend):
            feedback = fetch_pr_feedback(repo, "20260217-42")

        assert feedback is not None
        assert feedback["comments"] == []
        assert feedback["ci_failures"][0]["name"] == "distributed / test"
        assert "distributed test timed out" in feedback["ci_failures"][0][
            "failed_log_excerpt"
        ]
        assert "failing PR check" in feedback["summary"]

    def test_fetches_pr_feedback_by_branch_when_job_has_no_pr_url(self, tmp_path):
        repo, backend = self._setup(tmp_path)

        def run_side_effect(cmd, check=True):
            if "gh pr list" in cmd:
                return CompletedProcess(
                    "", 0, "https://github.com/pytorch/pytorch/pull/88\n", ""
                )
            if "gh api repos/pytorch/pytorch/issues/88/comments" in cmd:
                return CompletedProcess(
                    "",
                    0,
                    '[{"body": "Address this comment.", "user": {"login": "human"}}]',
                    "",
                )
            if "gh api repos/pytorch/pytorch/pulls/88/comments" in cmd:
                return CompletedProcess("", 0, "[]", "")
            if "gh api repos/pytorch/pytorch/pulls/88/reviews" in cmd:
                return CompletedProcess("", 0, "[]", "")
            return CompletedProcess("", 0, "")

        backend.run = MagicMock(side_effect=run_side_effect)
        with patch("ptq.application.pr_service.backend_for_job", return_value=backend):
            feedback = fetch_pr_feedback(repo, "20260217-42")

        assert feedback is not None
        assert repo.get("20260217-42").pr_url == "https://github.com/pytorch/pytorch/pull/88"
        assert feedback["comments"][0]["body"] == "Address this comment."

    def test_sync_existing_pr_branch_discovers_pr_by_branch(self, tmp_path):
        repo, backend = self._setup(tmp_path)

        def run_side_effect(cmd, check=True):
            if "gh pr list" in cmd:
                return CompletedProcess(
                    "", 0, "https://github.com/pytorch/pytorch/pull/88\n", ""
                )
            if "git ls-remote --exit-code --heads origin ptq/42" in cmd:
                return CompletedProcess("", 0, "abc\trefs/heads/ptq/42\n", "")
            if "fetch --no-recurse-submodules origin ptq/42" in cmd:
                return CompletedProcess("", 0, "", "")
            if "git status --porcelain" in cmd:
                return CompletedProcess("", 0, "", "")
            if "git branch --show-current" in cmd:
                return CompletedProcess("", 0, "ptq/42\n", "")
            if "git rebase FETCH_HEAD" in cmd:
                return CompletedProcess("", 0, "", "")
            return CompletedProcess("", 0, "")

        backend.run = MagicMock(side_effect=run_side_effect)
        with patch("ptq.application.pr_service.backend_for_job", return_value=backend):
            pr_url = sync_existing_pr_branch(repo, "20260217-42")

        assert pr_url == "https://github.com/pytorch/pytorch/pull/88"
        assert repo.get("20260217-42").pr_url == pr_url
        commands = [call.args[0] for call in backend.run.call_args_list]
        assert any(
            "fetch --no-recurse-submodules origin ptq/42" in cmd
            for cmd in commands
        )
        assert any("git rebase FETCH_HEAD" in cmd for cmd in commands)

    def test_replies_to_resolved_pr_comments_with_bot_prefix(self, tmp_path):
        repo, backend = self._setup(tmp_path)

        def run_side_effect(cmd, check=True):
            if "cat ~/ptq_workspace/jobs/20260217-42/status.json" in cmd:
                return CompletedProcess(
                    "",
                    0,
                    (
                        '{"resolved_pr_comments": ['
                        '{"comment_id": 222, "kind": "inline", '
                        '"resolution": "Added no_grad coverage."},'
                        '{"comment_id": 111, "kind": "conversation", '
                        '"comment_url": "https://github.com/pytorch/pytorch/pull/99#issuecomment-111", '
                        '"resolution": "Updated the PR description."}'
                        "]} "
                    ),
                    "",
                )
            if "cat ~/ptq_workspace/jobs/20260217-42/" in cmd:
                return CompletedProcess("", 1, "", "")
            if "git remote get-url" in cmd:
                return CompletedProcess("", 0, "git@github.com:pytorch/pytorch.git\n")
            if "gh pr create" in cmd:
                return CompletedProcess(
                    "", 0, "https://github.com/pytorch/pytorch/pull/99\n"
                )
            if "gh api repos/pytorch/pytorch/issues/99/comments" in cmd:
                return CompletedProcess("", 0, "[]", "")
            if "gh api repos/pytorch/pytorch/pulls/99/comments" in cmd:
                return CompletedProcess("", 0, "[]", "")
            if "gh api -X POST repos/pytorch/pytorch/pulls/99/comments/222/replies" in cmd:
                return CompletedProcess("", 0, "", "")
            if "gh pr comment https://github.com/pytorch/pytorch/pull/99" in cmd:
                return CompletedProcess("", 0, "", "")
            return CompletedProcess("", 0, "")

        backend.run = MagicMock(side_effect=run_side_effect)
        with patch("ptq.application.pr_service.backend_for_job", return_value=backend):
            create_pr(repo, "20260217-42", human_note="Trivial fix")

        inline_replies = [
            call
            for call in backend.run.call_args_list
            if "gh api -X POST repos/pytorch/pytorch/pulls/99/comments/222/replies"
            in str(call)
        ]
        timeline_replies = [
            call
            for call in backend.run.call_args_list
            if "gh pr comment https://github.com/pytorch/pytorch/pull/99"
            in str(call)
        ]
        assert len(inline_replies) == 1
        assert len(timeline_replies) == 1
        assert "[bot] Resolved in the latest update. Added no_grad coverage." in str(
            inline_replies[0]
        )
        assert "[bot] Resolved in the latest update. Updated the PR description." in str(
            timeline_replies[0]
        )
        assert "<!-- ptq:resolution:222 -->" in str(inline_replies[0])
        assert "<!-- ptq:resolution:111 -->" in str(timeline_replies[0])

    def test_resolution_reply_is_short(self, tmp_path):
        repo, backend = self._setup(tmp_path)
        long_resolution = (
            "Addressed in the diff: torch/distributed/tensor/_api.py now carries "
            "a long BC paragraph explaining every scenario. The PR description "
            "also contains extensive analysis that should not be pasted into a "
            "GitHub comment reply."
        )

        def run_side_effect(cmd, check=True):
            if "cat ~/ptq_workspace/jobs/20260217-42/status.json" in cmd:
                return CompletedProcess(
                    "",
                    0,
                    (
                        '{"resolved_pr_comments": ['
                        '{"comment_id": 222, "kind": "inline", '
                        f'"resolution": {long_resolution!r}'
                        "}]}"
                    ).replace("'", '"'),
                    "",
                )
            if "cat ~/ptq_workspace/jobs/20260217-42/" in cmd:
                return CompletedProcess("", 1, "", "")
            if "git remote get-url" in cmd:
                return CompletedProcess("", 0, "git@github.com:pytorch/pytorch.git\n")
            if "gh pr create" in cmd:
                return CompletedProcess(
                    "", 0, "https://github.com/pytorch/pytorch/pull/99\n"
                )
            if "gh api repos/pytorch/pytorch/issues/99/comments" in cmd:
                return CompletedProcess("", 0, "[]", "")
            if "gh api repos/pytorch/pytorch/pulls/99/comments" in cmd:
                return CompletedProcess("", 0, "[]", "")
            return CompletedProcess("", 0, "")

        backend.run = MagicMock(side_effect=run_side_effect)
        with patch("ptq.application.pr_service.backend_for_job", return_value=backend):
            create_pr(repo, "20260217-42", human_note="Trivial fix")

        inline_replies = [
            call
            for call in backend.run.call_args_list
            if "gh api -X POST repos/pytorch/pytorch/pulls/99/comments/222/replies"
            in str(call)
        ]
        assert len(inline_replies) == 1
        reply = str(inline_replies[0])
        assert "The PR description also contains extensive analysis" not in reply
        assert "Resolved in the latest update." in reply

    def test_does_not_duplicate_resolution_replies(self, tmp_path):
        repo, backend = self._setup(tmp_path)

        def run_side_effect(cmd, check=True):
            if "cat ~/ptq_workspace/jobs/20260217-42/status.json" in cmd:
                return CompletedProcess(
                    "",
                    0,
                    (
                        '{"resolved_pr_comments": ['
                        '{"comment_id": 222, "kind": "inline", '
                        '"resolution": "Added no_grad coverage."}'
                        "]}"
                    ),
                    "",
                )
            if "cat ~/ptq_workspace/jobs/20260217-42/" in cmd:
                return CompletedProcess("", 1, "", "")
            if "git remote get-url" in cmd:
                return CompletedProcess("", 0, "git@github.com:pytorch/pytorch.git\n")
            if "gh pr create" in cmd:
                return CompletedProcess(
                    "", 0, "https://github.com/pytorch/pytorch/pull/99\n"
                )
            if "gh api repos/pytorch/pytorch/issues/99/comments" in cmd:
                return CompletedProcess("", 0, "[]", "")
            if "gh api repos/pytorch/pytorch/pulls/99/comments" in cmd:
                return CompletedProcess(
                    "",
                    0,
                    '[{"body": "[bot] Resolved.\\n\\n<!-- ptq:resolution:222 -->"}]',
                    "",
                )
            return CompletedProcess("", 0, "")

        backend.run = MagicMock(side_effect=run_side_effect)
        with patch("ptq.application.pr_service.backend_for_job", return_value=backend):
            create_pr(repo, "20260217-42", human_note="Trivial fix")

        inline_replies = [
            call
            for call in backend.run.call_args_list
            if "gh api -X POST repos/pytorch/pytorch/pulls/99/comments/222/replies"
            in str(call)
        ]
        assert not inline_replies
